// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventcreator_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventProvider creates a new instance of MockEventProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockEventProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockEventProvider is an autogenerated mock type for the EventProvider type
type MockEventProvider struct {
	mock.Mock
}

type MockEventProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventProvider) EXPECT() *MockEventProvider_Expecter {
	return &MockEventProvider_Expecter{mock: &_m.Mock}
}

// LoadEvents provides a mock function for the type MockEventProvider
func (_mock *MockEventProvider) LoadEvents(ctx context.Context) ([]models.ReportCronEvent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadEvents")
	}

	var r0 []models.ReportCronEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.ReportCronEvent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.ReportCronEvent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReportCronEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventProvider_LoadEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadEvents'
type MockEventProvider_LoadEvents_Call struct {
	*mock.Call
}

// LoadEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventProvider_Expecter) LoadEvents(ctx any) *MockEventProvider_LoadEvents_Call {
	return &MockEventProvider_LoadEvents_Call{Call: _e.mock.On("LoadEvents", ctx)}
}

func (_c *MockEventProvider_LoadEvents_Call) Run(run func(ctx context.Context)) *MockEventProvider_LoadEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventProvider_LoadEvents_Call) Return(reportCronEvents []models.ReportCronEvent, err error) *MockEventProvider_LoadEvents_Call {
	_c.Call.Return(reportCronEvents, err)
	return _c
}

func (_c *MockEventProvider_LoadEvents_Call) RunAndReturn(run func(ctx context.Context) ([]models.ReportCronEvent, error)) *MockEventProvider_LoadEvents_Call {
	_c.Call.Return(run)
	return _c
}

// LoadEventsByCronName provides a mock function for the type MockEventProvider
func (_mock *MockEventProvider) LoadEventsByCronName(ctx context.Context, name string) ([]models.ReportCronEvent, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for LoadEventsByCronName")
	}

	var r0 []models.ReportCronEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.ReportCronEvent, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.ReportCronEvent); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReportCronEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventProvider_LoadEventsByCronName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadEventsByCronName'
type MockEventProvider_LoadEventsByCronName_Call struct {
	*mock.Call
}

// LoadEventsByCronName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockEventProvider_Expecter) LoadEventsByCronName(ctx any, name any) *MockEventProvider_LoadEventsByCronName_Call {
	return &MockEventProvider_LoadEventsByCronName_Call{Call: _e.mock.On("LoadEventsByCronName", ctx, name)}
}

func (_c *MockEventProvider_LoadEventsByCronName_Call) Run(run func(ctx context.Context, name string)) *MockEventProvider_LoadEventsByCronName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventProvider_LoadEventsByCronName_Call) Return(reportCronEvents []models.ReportCronEvent, err error) *MockEventProvider_LoadEventsByCronName_Call {
	_c.Call.Return(reportCronEvents, err)
	return _c
}

func (_c *MockEventProvider_LoadEventsByCronName_Call) RunAndReturn(run func(ctx context.Context, name string) ([]models.ReportCronEvent, error)) *MockEventProvider_LoadEventsByCronName_Call {
	_c.Call.Return(run)
	return _c
}
