// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sheduler_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSheduleLoader creates a new instance of MockSheduleLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSheduleLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSheduleLoader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSheduleLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSheduleLoader is an autogenerated mock type for the SheduleLoader type
type MockSheduleLoader struct {
	mock.Mock
}

type MockSheduleLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSheduleLoader) EXPECT() *MockSheduleLoader_Expecter {
	return &MockSheduleLoader_Expecter{mock: &_m.Mock}
}

// LoadActive provides a mock function for the type MockSheduleLoader
func (_mock *MockSheduleLoader) LoadActive(ctx context.Context) ([]models.SheduleUnit, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadActive")
	}

	var r0 []models.SheduleUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.SheduleUnit, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.SheduleUnit); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SheduleUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSheduleLoader_LoadActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadActive'
type MockSheduleLoader_LoadActive_Call struct {
	*mock.Call
}

// LoadActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSheduleLoader_Expecter) LoadActive(ctx any) *MockSheduleLoader_LoadActive_Call {
	return &MockSheduleLoader_LoadActive_Call{Call: _e.mock.On("LoadActive", ctx)}
}

func (_c *MockSheduleLoader_LoadActive_Call) Run(run func(ctx context.Context)) *MockSheduleLoader_LoadActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSheduleLoader_LoadActive_Call) Return(sheduleUnits []models.SheduleUnit, err error) *MockSheduleLoader_LoadActive_Call {
	_c.Call.Return(sheduleUnits, err)
	return _c
}

func (_c *MockSheduleLoader_LoadActive_Call) RunAndReturn(run func(ctx context.Context) ([]models.SheduleUnit, error)) *MockSheduleLoader_LoadActive_Call {
	_c.Call.Return(run)
	return _c
}
