version: "2"
run:
  issues-exit-code: 1
linters:
  enable:
    - bodyclose
    - canonicalheader
    - contextcheck
    - spancheck
    - rowserrcheck
    - sqlclosecheck
    - gosec
    - cyclop
    - gocognit
    - nestif
    - asciicheck
    - errname
    - errcheck
    - errchkjson
    - nilerr
    - ineffassign
    - unused
    - unparam
    - unconvert	
    - perfsprint
    - usestdlibvars
    - noctx
    - ireturn
    - tparallel
    - revive
    - staticcheck
    - gocritic
    - loggercheck
  default: none
  disable:
  settings:
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
