# supported golangci-lint version = 2.6.0+
version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - errname
    - funcorder
    - modernize
    - nakedret
    - nilerr
    - staticcheck
    - unconvert
    - unused

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - appendAssign
        - hugeParam
        - rangeValCopy
        - paramTypeCombine
        - unnamedResult

    revive:
      ignore-generated-header: true
      severity: warning
      rules:
        - name: indent-error-flow

    gosec:
      excludes:
        - G104
        - G203

    staticcheck:
      checks: ["all", "-ST1003"]

    unused:
      field-writes-are-uses: true
      exported-fields-are-used: true

    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Print
        - fmt.Println
        - (*log.Logger).Print
        - (*log.Logger).Printf
        - (*log.Logger).Println

  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
