services:
  bottst:
    build: .
    container_name: bottst
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/sbot/config/local_docker.yaml
    volumes:
      - ./config:/sbot/config:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  db:
    image: postgres:9.3
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bottst
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./migrations/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:
    name: bottst
