// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportStore creates a new instance of MockReportStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReportStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReportStore is an autogenerated mock type for the ReportStore type
type MockReportStore struct {
	mock.Mock
}

type MockReportStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportStore) EXPECT() *MockReportStore_Expecter {
	return &MockReportStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReportStore
func (_mock *MockReportStore) Create(ctx context.Context, report models.Report) (int64, error) {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Report) (int64, error)); ok {
		return returnFunc(ctx, report)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Report) int64); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Report) error); ok {
		r1 = returnFunc(ctx, report)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReportStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - report models.Report
func (_e *MockReportStore_Expecter) Create(ctx any, report any) *MockReportStore_Create_Call {
	return &MockReportStore_Create_Call{Call: _e.mock.On("Create", ctx, report)}
}

func (_c *MockReportStore_Create_Call) Run(run func(ctx context.Context, report models.Report)) *MockReportStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Report
		if args[1] != nil {
			arg1 = args[1].(models.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportStore_Create_Call) Return(n int64, err error) *MockReportStore_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReportStore_Create_Call) RunAndReturn(run func(ctx context.Context, report models.Report) (int64, error)) *MockReportStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockReportStore
func (_mock *MockReportStore) Load(ctx context.Context) ([]models.Report, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Report, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Report); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockReportStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReportStore_Expecter) Load(ctx any) *MockReportStore_Load_Call {
	return &MockReportStore_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockReportStore_Load_Call) Run(run func(ctx context.Context)) *MockReportStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportStore_Load_Call) Return(reports []models.Report, err error) *MockReportStore_Load_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *MockReportStore_Load_Call) RunAndReturn(run func(ctx context.Context) ([]models.Report, error)) *MockReportStore_Load_Call {
	_c.Call.Return(run)
	return _c
}
