// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlcgen

import (
	"context"
)

const createChat = `-- name: CreateChat :one
insert into chats(chat_id, title, type, description, is_active, ch_type)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type CreateChatParams struct {
	ChatID      int64
	Title       *string
	Type        string
	Description *string
	IsActive    bool
	ChType      string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (int32, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.ChatID,
		arg.Title,
		arg.Type,
		arg.Description,
		arg.IsActive,
		arg.ChType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteChat = `-- name: DeleteChat :exec
delete from chats where chat_id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deleteChat, chatID)
	return err
}

const findChatIDByChatID = `-- name: FindChatIDByChatID :one

select id from chats where chat_id = $1
`

// chat.sql
// CRUD-запросы для таблицы chats, используемые ChatStore и
// ReportStore.Create (FindChatIDByChatID/CreateChat, добавлены в фазе 1).
func (q *Queries) FindChatIDByChatID(ctx context.Context, chatID int64) (int32, error) {
	row := q.db.QueryRow(ctx, findChatIDByChatID, chatID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getChatByTitle = `-- name: GetChatByTitle :one
select id, chat_id, title, type, description, is_active, ch_type
from chats
where title = $1
limit 1
`

func (q *Queries) GetChatByTitle(ctx context.Context, title *string) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByTitle, title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.Type,
		&i.Description,
		&i.IsActive,
		&i.ChType,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
select id, chat_id, title, type, description, is_active, ch_type
from chats
where is_active = false
`

func (q *Queries) ListChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Title,
			&i.Type,
			&i.Description,
			&i.IsActive,
			&i.ChType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
