// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlcgen

import (
	"context"
)

const createChat = `-- name: CreateChat :one
insert into chats(chat_id, title, type, description, is_active, ch_type)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type CreateChatParams struct {
	ChatID      int64
	Title       *string
	Type        string
	Description *string
	IsActive    bool
	ChType      string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (int32, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.ChatID,
		arg.Title,
		arg.Type,
		arg.Description,
		arg.IsActive,
		arg.ChType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findChatIDByChatID = `-- name: FindChatIDByChatID :one

select id from chats where chat_id = $1
`

// chat.sql
// Phase 1 only adds the two queries ReportStore.Create's transaction needs
// to resolve/create a chat by chat_id. Full chat CRUD (GetByTitle, ListChats,
// DeleteChat) is Phase 2's job — do not add them here.
func (q *Queries) FindChatIDByChatID(ctx context.Context, chatID int64) (int32, error) {
	row := q.db.QueryRow(ctx, findChatIDByChatID, chatID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
