// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron.sql

package sqlcgen

import (
	"context"
)

const listActiveCrons = `-- name: ListActiveCrons :many
select cron, name, event_type from crons where is_active = true
`

type ListActiveCronsRow struct {
	Cron      string
	Name      string
	EventType int32
}

func (q *Queries) ListActiveCrons(ctx context.Context) ([]ListActiveCronsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCrons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCronsRow
	for rows.Next() {
		var i ListActiveCronsRow
		if err := rows.Scan(&i.Cron, &i.Name, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForActiveReports = `-- name: ListEventsForActiveReports :many
select c.name as cron_name, r.name as report_name
from report_crons rc join crons c on c.id = rc.cron_id
join reports r on r.id = rc.report_id where r.active = true
`

type ListEventsForActiveReportsRow struct {
	CronName   string
	ReportName string
}

func (q *Queries) ListEventsForActiveReports(ctx context.Context) ([]ListEventsForActiveReportsRow, error) {
	rows, err := q.db.Query(ctx, listEventsForActiveReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsForActiveReportsRow
	for rows.Next() {
		var i ListEventsForActiveReportsRow
		if err := rows.Scan(&i.CronName, &i.ReportName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForActiveReportsByCronName = `-- name: ListEventsForActiveReportsByCronName :many
select c.name as cron_name, r.name as report_name
from report_crons rc join crons c on c.id = rc.cron_id
join reports r on r.id = rc.report_id
where c.name = $1 and r.active = true
`

type ListEventsForActiveReportsByCronNameRow struct {
	CronName   string
	ReportName string
}

func (q *Queries) ListEventsForActiveReportsByCronName(ctx context.Context, name string) ([]ListEventsForActiveReportsByCronNameRow, error) {
	rows, err := q.db.Query(ctx, listEventsForActiveReportsByCronName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsForActiveReportsByCronNameRow
	for rows.Next() {
		var i ListEventsForActiveReportsByCronNameRow
		if err := rows.Scan(&i.CronName, &i.ReportName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
