// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lua_script.sql

package sqlcgen

import (
	"context"
)

const getScriptByName = `-- name: GetScriptByName :one
select script from lua_scripts where name = $1
`

func (q *Queries) GetScriptByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getScriptByName, name)
	var script string
	err := row.Scan(&script)
	return script, err
}

const saveScriptIfAbsent = `-- name: SaveScriptIfAbsent :exec
insert into lua_scripts(name, script) values ($1, $2)
on conflict (name) do nothing
`

type SaveScriptIfAbsentParams struct {
	Name   string
	Script string
}

func (q *Queries) SaveScriptIfAbsent(ctx context.Context, arg SaveScriptIfAbsentParams) error {
	_, err := q.db.Exec(ctx, saveScriptIfAbsent, arg.Name, arg.Script)
	return err
}
