// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleUser    UserRole = "user"
	UserRolePrimary UserRole = "primary"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Chat struct {
	ID          int32
	ChatID      int64
	Title       *string
	Type        string
	Description *string
	IsActive    bool
	ChType      string
}

type Cron struct {
	ID          int32
	Cron        string
	Name        string
	Description *string
	IsActive    bool
	EventType   int32
}

type EmailTemplate struct {
	ID      int32
	Dest    []string
	Copy    []string
	Subject string
	Body    *string
}

type Evaluate struct {
	ID   int32
	Expr string
}

type ExportFormat struct {
	ID     int32
	Format *string
}

type LuaScript struct {
	ID     int32
	Name   string
	Script string
}

type Pipeline struct {
	ID       int32
	Pipeline []byte
}

type PublicReport struct {
	ID       int32
	PublicID pgtype.UUID
	ReportID int64
}

type Query struct {
	ID       int32
	CardUuid string
	Title    string
	QType    string
	Params   []byte
}

type Recipient struct {
	ID                      int32
	Name                    string
	Config                  []byte
	RemotePath              *string
	ChatID                  *int32
	ThreadID                *int32
	EmailID                 *int32
	Type                    *string
	NeedDeleteAfterEndOfDay *bool
}

type Report struct {
	ID           int32
	Name         string
	Active       bool
	Title        string
	EvalID       int64
	AccessFromLk bool
	PipelineID   *int64
}

type ReportCron struct {
	ReportID int32
	CronID   int32
}

type ReportQuery struct {
	ReportID int32
	QueryID  int32
}

type ReportTemplate struct {
	ReportID   int32
	TemplateID int32
}

type ReportsExport struct {
	ReportID  *int32
	FormatID  *int32
	FileName  *string
	SortOrder []byte
}

type ReportsRecipient struct {
	ReportID    *int32
	RecipientID *int32
}

type SentMessage struct {
	ID           int32
	ChatID       int64
	ThreadID     int32
	MessageID    int64
	Title        string
	SentAt       pgtype.Timestamptz
	Deleted      bool
	ReportName   string
	MessageIDStr *string
	ChType       string
}

type Template struct {
	ID           int32
	TemplateText *string
	Title        *string
	Type         string
}

type User struct {
	ID         int32
	TelegramID int64
	Username   *string
	FirstName  *string
	LastName   *string
	Role       UserRole
}
