// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package sqlcgen

import (
	"context"
)

const reportExistsByName = `-- name: ReportExistsByName :one
select exists(select 1 from reports where name = $1)
`

func (q *Queries) ReportExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, reportExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
