// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportsForLK = `-- name: CountReportsForLK :one
select count(*) from reports where access_from_lk = true
`

func (q *Queries) CountReportsForLK(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsForLK)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCron = `-- name: CreateCron :one
insert into crons(cron, name, description, is_active, event_type) values ($1, $2, $3, $4, $5) returning id
`

type CreateCronParams struct {
	Cron        string
	Name        string
	Description *string
	IsActive    bool
	EventType   int32
}

func (q *Queries) CreateCron(ctx context.Context, arg CreateCronParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCron,
		arg.Cron,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.EventType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createEmailTemplate = `-- name: CreateEmailTemplate :one
insert into email_templates(dest, copy, subject, body) values ($1, $2, $3, $4) returning id
`

type CreateEmailTemplateParams struct {
	Dest    []string
	Copy    []string
	Subject string
	Body    *string
}

func (q *Queries) CreateEmailTemplate(ctx context.Context, arg CreateEmailTemplateParams) (int32, error) {
	row := q.db.QueryRow(ctx, createEmailTemplate,
		arg.Dest,
		arg.Copy,
		arg.Subject,
		arg.Body,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createEvaluation = `-- name: CreateEvaluation :one
insert into evaluate(expr) values ($1) returning id
`

func (q *Queries) CreateEvaluation(ctx context.Context, expr string) (int32, error) {
	row := q.db.QueryRow(ctx, createEvaluation, expr)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createExportFormat = `-- name: CreateExportFormat :one
insert into export_formats(format) values ($1) returning id
`

func (q *Queries) CreateExportFormat(ctx context.Context, format *string) (int32, error) {
	row := q.db.QueryRow(ctx, createExportFormat, format)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPipeline = `-- name: CreatePipeline :one
insert into pipelines(pipeline) values ($1) returning id
`

func (q *Queries) CreatePipeline(ctx context.Context, pipeline []byte) (int32, error) {
	row := q.db.QueryRow(ctx, createPipeline, pipeline)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createQuery = `-- name: CreateQuery :one
insert into queries(card_uuid, title, q_type, params) values ($1, $2, $3, $4) returning id
`

type CreateQueryParams struct {
	CardUuid string
	Title    string
	QType    string
	Params   []byte
}

func (q *Queries) CreateQuery(ctx context.Context, arg CreateQueryParams) (int32, error) {
	row := q.db.QueryRow(ctx, createQuery,
		arg.CardUuid,
		arg.Title,
		arg.QType,
		arg.Params,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createRecipient = `-- name: CreateRecipient :one
insert into recipients(name, config, remote_path, chat_id, thread_id, email_id, type, need_delete_after_end_of_day)
values ($1, '{}', $2, $3, $4, $5, $6, $7)
returning id
`

type CreateRecipientParams struct {
	Name                    string
	RemotePath              *string
	ChatID                  *int32
	ThreadID                *int32
	EmailID                 *int32
	Type                    *string
	NeedDeleteAfterEndOfDay *bool
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRecipient,
		arg.Name,
		arg.RemotePath,
		arg.ChatID,
		arg.ThreadID,
		arg.EmailID,
		arg.Type,
		arg.NeedDeleteAfterEndOfDay,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createReport = `-- name: CreateReport :one
insert into reports(name, title, eval_id, pipeline_id, access_from_lk, active)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type CreateReportParams struct {
	Name         string
	Title        string
	EvalID       int64
	PipelineID   *int64
	AccessFromLk bool
	Active       bool
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (int32, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.Name,
		arg.Title,
		arg.EvalID,
		arg.PipelineID,
		arg.AccessFromLk,
		arg.Active,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTemplate = `-- name: CreateTemplate :one
insert into templates(template_text, title, type) values ($1, $2, $3) returning id
`

type CreateTemplateParams struct {
	TemplateText *string
	Title        *string
	Type         string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.TemplateText, arg.Title, arg.Type)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findCronIDByNameAndExpr = `-- name: FindCronIDByNameAndExpr :one
select id from crons where name = $1 and cron = $2
`

type FindCronIDByNameAndExprParams struct {
	Name string
	Cron string
}

func (q *Queries) FindCronIDByNameAndExpr(ctx context.Context, arg FindCronIDByNameAndExprParams) (int32, error) {
	row := q.db.QueryRow(ctx, findCronIDByNameAndExpr, arg.Name, arg.Cron)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findEvaluationIDByExpr = `-- name: FindEvaluationIDByExpr :one

select id from evaluate where expr = $1
`

// Write-side queries for ReportStore.Create's transaction (Task 7).
func (q *Queries) FindEvaluationIDByExpr(ctx context.Context, expr string) (int32, error) {
	row := q.db.QueryRow(ctx, findEvaluationIDByExpr, expr)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findExportFormatIDByFormat = `-- name: FindExportFormatIDByFormat :one
select id from export_formats where format = $1
`

func (q *Queries) FindExportFormatIDByFormat(ctx context.Context, format *string) (int32, error) {
	row := q.db.QueryRow(ctx, findExportFormatIDByFormat, format)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findQueryIDByUUIDAndTitle = `-- name: FindQueryIDByUUIDAndTitle :one
select id from queries where card_uuid = $1 and title = $2
`

type FindQueryIDByUUIDAndTitleParams struct {
	CardUuid string
	Title    string
}

func (q *Queries) FindQueryIDByUUIDAndTitle(ctx context.Context, arg FindQueryIDByUUIDAndTitleParams) (int32, error) {
	row := q.db.QueryRow(ctx, findQueryIDByUUIDAndTitle, arg.CardUuid, arg.Title)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findRecipientIDByName = `-- name: FindRecipientIDByName :one
select id from recipients where name = $1
`

func (q *Queries) FindRecipientIDByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, findRecipientIDByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findTemplateIDByTitleAndType = `-- name: FindTemplateIDByTitleAndType :one
select id from templates where title = $1 and type = $2
`

type FindTemplateIDByTitleAndTypeParams struct {
	Title *string
	Type  string
}

func (q *Queries) FindTemplateIDByTitleAndType(ctx context.Context, arg FindTemplateIDByTitleAndTypeParams) (int32, error) {
	row := q.db.QueryRow(ctx, findTemplateIDByTitleAndType, arg.Title, arg.Type)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getActiveReportRowByName = `-- name: GetActiveReportRowByName :one
select r.id, r.name, r.title, r.active, r.access_from_lk, r.pipeline_id, e.expr as evaluation
from reports r
left join evaluate e on e.id = r.eval_id
where r.name = $1 and r.active = true
limit 1
`

type GetActiveReportRowByNameRow struct {
	ID           int32
	Name         string
	Title        string
	Active       bool
	AccessFromLk bool
	PipelineID   *int64
	Evaluation   *string
}

func (q *Queries) GetActiveReportRowByName(ctx context.Context, name string) (GetActiveReportRowByNameRow, error) {
	row := q.db.QueryRow(ctx, getActiveReportRowByName, name)
	var i GetActiveReportRowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Active,
		&i.AccessFromLk,
		&i.PipelineID,
		&i.Evaluation,
	)
	return i, err
}

const getAnyReportRowByName = `-- name: GetAnyReportRowByName :one
select r.id, r.name, r.title, r.active, r.access_from_lk, r.pipeline_id, e.expr as evaluation
from reports r
left join evaluate e on e.id = r.eval_id
where r.name = $1
limit 1
`

type GetAnyReportRowByNameRow struct {
	ID           int32
	Name         string
	Title        string
	Active       bool
	AccessFromLk bool
	PipelineID   *int64
	Evaluation   *string
}

func (q *Queries) GetAnyReportRowByName(ctx context.Context, name string) (GetAnyReportRowByNameRow, error) {
	row := q.db.QueryRow(ctx, getAnyReportRowByName, name)
	var i GetAnyReportRowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Active,
		&i.AccessFromLk,
		&i.PipelineID,
		&i.Evaluation,
	)
	return i, err
}

const getPipelineByID = `-- name: GetPipelineByID :one
select pipeline from pipelines where id = $1::bigint
`

func (q *Queries) GetPipelineByID(ctx context.Context, dollar_1 int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPipelineByID, dollar_1)
	var pipeline []byte
	err := row.Scan(&pipeline)
	return pipeline, err
}

const getReportIDByPublicID = `-- name: GetReportIDByPublicID :one
select report_id from public_reports where public_id = $1 limit 1
`

func (q *Queries) GetReportIDByPublicID(ctx context.Context, publicID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReportIDByPublicID, publicID)
	var report_id int64
	err := row.Scan(&report_id)
	return report_id, err
}

const getReportRowByID = `-- name: GetReportRowByID :one
select r.id, r.name, r.title, r.active, r.access_from_lk, r.pipeline_id, e.expr as evaluation
from reports r
left join evaluate e on e.id = r.eval_id
where r.id = $1::bigint
limit 1
`

type GetReportRowByIDRow struct {
	ID           int32
	Name         string
	Title        string
	Active       bool
	AccessFromLk bool
	PipelineID   *int64
	Evaluation   *string
}

func (q *Queries) GetReportRowByID(ctx context.Context, dollar_1 int64) (GetReportRowByIDRow, error) {
	row := q.db.QueryRow(ctx, getReportRowByID, dollar_1)
	var i GetReportRowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Active,
		&i.AccessFromLk,
		&i.PipelineID,
		&i.Evaluation,
	)
	return i, err
}

const linkCronToReport = `-- name: LinkCronToReport :exec
insert into report_crons(report_id, cron_id) values ($1, $2)
`

type LinkCronToReportParams struct {
	ReportID int32
	CronID   int32
}

func (q *Queries) LinkCronToReport(ctx context.Context, arg LinkCronToReportParams) error {
	_, err := q.db.Exec(ctx, linkCronToReport, arg.ReportID, arg.CronID)
	return err
}

const linkExportToReport = `-- name: LinkExportToReport :exec
insert into reports_export(report_id, format_id, file_name, sort_order) values ($1, $2, $3, $4)
`

type LinkExportToReportParams struct {
	ReportID  *int32
	FormatID  *int32
	FileName  *string
	SortOrder []byte
}

func (q *Queries) LinkExportToReport(ctx context.Context, arg LinkExportToReportParams) error {
	_, err := q.db.Exec(ctx, linkExportToReport,
		arg.ReportID,
		arg.FormatID,
		arg.FileName,
		arg.SortOrder,
	)
	return err
}

const linkQueryToReport = `-- name: LinkQueryToReport :exec
insert into report_queries(report_id, query_id) values ($1, $2)
`

type LinkQueryToReportParams struct {
	ReportID int32
	QueryID  int32
}

func (q *Queries) LinkQueryToReport(ctx context.Context, arg LinkQueryToReportParams) error {
	_, err := q.db.Exec(ctx, linkQueryToReport, arg.ReportID, arg.QueryID)
	return err
}

const linkRecipientToReport = `-- name: LinkRecipientToReport :exec
insert into reports_recipients(report_id, recipient_id) values ($1, $2)
`

type LinkRecipientToReportParams struct {
	ReportID    *int32
	RecipientID *int32
}

func (q *Queries) LinkRecipientToReport(ctx context.Context, arg LinkRecipientToReportParams) error {
	_, err := q.db.Exec(ctx, linkRecipientToReport, arg.ReportID, arg.RecipientID)
	return err
}

const linkTemplateToReport = `-- name: LinkTemplateToReport :exec
insert into report_templates(report_id, template_id) values ($1, $2)
`

type LinkTemplateToReportParams struct {
	ReportID   int32
	TemplateID int32
}

func (q *Queries) LinkTemplateToReport(ctx context.Context, arg LinkTemplateToReportParams) error {
	_, err := q.db.Exec(ctx, linkTemplateToReport, arg.ReportID, arg.TemplateID)
	return err
}

const listActiveReportRows = `-- name: ListActiveReportRows :many
select r.id, r.name, r.title, r.active, r.access_from_lk, r.pipeline_id, e.expr as evaluation
from reports r
left join evaluate e on e.id = r.eval_id
where r.active = true
`

type ListActiveReportRowsRow struct {
	ID           int32
	Name         string
	Title        string
	Active       bool
	AccessFromLk bool
	PipelineID   *int64
	Evaluation   *string
}

func (q *Queries) ListActiveReportRows(ctx context.Context) ([]ListActiveReportRowsRow, error) {
	rows, err := q.db.Query(ctx, listActiveReportRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveReportRowsRow
	for rows.Next() {
		var i ListActiveReportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Active,
			&i.AccessFromLk,
			&i.PipelineID,
			&i.Evaluation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByReportID = `-- name: ListCardsByReportID :many
select q.card_uuid, q.title, q.q_type, q.params
from report_queries rq
join queries q on q.id = rq.query_id
where rq.report_id = $1::bigint
`

type ListCardsByReportIDRow struct {
	CardUuid string
	Title    string
	QType    string
	Params   []byte
}

func (q *Queries) ListCardsByReportID(ctx context.Context, dollar_1 int64) ([]ListCardsByReportIDRow, error) {
	rows, err := q.db.Query(ctx, listCardsByReportID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsByReportIDRow
	for rows.Next() {
		var i ListCardsByReportIDRow
		if err := rows.Scan(
			&i.CardUuid,
			&i.Title,
			&i.QType,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronsByReportID = `-- name: ListCronsByReportID :many
select c.cron, c.name, c.description, c.is_active, c.event_type
from report_crons rc
join crons c on c.id = rc.cron_id
where rc.report_id = $1::bigint
`

type ListCronsByReportIDRow struct {
	Cron        string
	Name        string
	Description *string
	IsActive    bool
	EventType   int32
}

func (q *Queries) ListCronsByReportID(ctx context.Context, dollar_1 int64) ([]ListCronsByReportIDRow, error) {
	rows, err := q.db.Query(ctx, listCronsByReportID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCronsByReportIDRow
	for rows.Next() {
		var i ListCronsByReportIDRow
		if err := rows.Scan(
			&i.Cron,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportsByReportID = `-- name: ListExportsByReportID :many
select ef.format, re.file_name, t.id as template_id, t.title as template_title,
       t.type as template_type, t.template_text, re.sort_order
from reports_export re
join export_formats ef on ef.id = re.format_id
left join report_templates rt on rt.report_id = re.report_id
left join templates t on t.id = rt.template_id
where re.report_id = $1::bigint
`

type ListExportsByReportIDRow struct {
	Format        *string
	FileName      *string
	TemplateID    *int32
	TemplateTitle *string
	TemplateType  *string
	TemplateText  *string
	SortOrder     []byte
}

func (q *Queries) ListExportsByReportID(ctx context.Context, dollar_1 int64) ([]ListExportsByReportIDRow, error) {
	rows, err := q.db.Query(ctx, listExportsByReportID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportsByReportIDRow
	for rows.Next() {
		var i ListExportsByReportIDRow
		if err := rows.Scan(
			&i.Format,
			&i.FileName,
			&i.TemplateID,
			&i.TemplateTitle,
			&i.TemplateType,
			&i.TemplateText,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsByReportID = `-- name: ListRecipientsByReportID :many
select
    rc.name,
    rc.config,
    rc.remote_path,
    rc.thread_id,
    rc.email_id,
    rc.type,
    rc.need_delete_after_end_of_day,
    e.dest,
    e.copy,
    e.subject,
    e.body,
    c.chat_id,
    c.title as chat_title,
    c.type as chat_type,
    c.description as chat_description,
    c.is_active as chat_is_active,
    c.ch_type as chat_ch_type
from reports_recipients rr
join recipients rc on rc.id = rr.recipient_id
left join chats c on c.id = rc.chat_id
left join email_templates e on e.id = rc.email_id
where rr.report_id = $1::bigint
`

type ListRecipientsByReportIDRow struct {
	Name                    string
	Config                  []byte
	RemotePath              *string
	ThreadID                *int32
	EmailID                 *int32
	Type                    *string
	NeedDeleteAfterEndOfDay *bool
	Dest                    []string
	Copy                    []string
	Subject                 *string
	Body                    *string
	ChatID                  *int64
	ChatTitle               *string
	ChatType                *string
	ChatDescription         *string
	ChatIsActive            *bool
	ChatChType              *string
}

func (q *Queries) ListRecipientsByReportID(ctx context.Context, dollar_1 int64) ([]ListRecipientsByReportIDRow, error) {
	rows, err := q.db.Query(ctx, listRecipientsByReportID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipientsByReportIDRow
	for rows.Next() {
		var i ListRecipientsByReportIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Config,
			&i.RemotePath,
			&i.ThreadID,
			&i.EmailID,
			&i.Type,
			&i.NeedDeleteAfterEndOfDay,
			&i.Dest,
			&i.Copy,
			&i.Subject,
			&i.Body,
			&i.ChatID,
			&i.ChatTitle,
			&i.ChatType,
			&i.ChatDescription,
			&i.ChatIsActive,
			&i.ChatChType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportLinkedCrons = `-- name: ListReportLinkedCrons :many
select c.cron as cron, c.name as name
from report_crons rc
left join crons c on c.id = rc.cron_id
left join reports r on rc.report_id = r.id
where c.is_active = true and r.name = $1
`

type ListReportLinkedCronsRow struct {
	Cron *string
	Name *string
}

func (q *Queries) ListReportLinkedCrons(ctx context.Context, name string) ([]ListReportLinkedCronsRow, error) {
	rows, err := q.db.Query(ctx, listReportLinkedCrons, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportLinkedCronsRow
	for rows.Next() {
		var i ListReportLinkedCronsRow
		if err := rows.Scan(&i.Cron, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportRows = `-- name: ListReportRows :many
select r.id, r.name, r.title, r.active, r.access_from_lk, r.pipeline_id, e.expr as evaluation
from reports r
left join evaluate e on e.id = r.eval_id
`

type ListReportRowsRow struct {
	ID           int32
	Name         string
	Title        string
	Active       bool
	AccessFromLk bool
	PipelineID   *int64
	Evaluation   *string
}

func (q *Queries) ListReportRows(ctx context.Context) ([]ListReportRowsRow, error) {
	rows, err := q.db.Query(ctx, listReportRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportRowsRow
	for rows.Next() {
		var i ListReportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Active,
			&i.AccessFromLk,
			&i.PipelineID,
			&i.Evaluation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForLK = `-- name: ListReportsForLK :many
select id, name, title from reports where access_from_lk = true order by id limit $1 offset $2
`

type ListReportsForLKParams struct {
	Limit  int32
	Offset int32
}

type ListReportsForLKRow struct {
	ID    int32
	Name  string
	Title string
}

func (q *Queries) ListReportsForLK(ctx context.Context, arg ListReportsForLKParams) ([]ListReportsForLKRow, error) {
	rows, err := q.db.Query(ctx, listReportsForLK, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsForLKRow
	for rows.Next() {
		var i ListReportsForLKRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportExistsByName = `-- name: ReportExistsByName :one

select exists(select 1 from reports where name = $1)
`

// report.sql
// Consolidated report/card/recipient/export/pipeline/cron queries.
// Replaces internal/repository/report.go, internal/orchestrator/orchestrator_repository.go,
// and internal/tg_bot/repository/report_repository.go's independent copies of this SQL.
func (q *Queries) ReportExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, reportExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
