// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sent_messages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllMarkedSentMessages = `-- name: DeleteAllMarkedSentMessages :execrows
delete from sent_messages where deleted = true
`

func (q *Queries) DeleteAllMarkedSentMessages(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllMarkedSentMessages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSentMessage = `-- name: InsertSentMessage :exec

insert into sent_messages(chat_id, thread_id, message_id, message_id_str, title, sent_at, report_name, ch_type)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSentMessageParams struct {
	ChatID       int64
	ThreadID     int32
	MessageID    int64
	MessageIDStr *string
	Title        string
	SentAt       pgtype.Timestamptz
	ReportName   string
	ChType       string
}

// sent_messages.sql
// Запросы для таблицы sent_messages, используемые SentMsgStore
// (internal/orchestrator.Deleter/Orchestrator). Переносит SQL из
// internal/orchestrator/result_repo.go (SentMsgRepository, фаза 3
// sqlc-миграции) без изменения текста запросов.
func (q *Queries) InsertSentMessage(ctx context.Context, arg InsertSentMessageParams) error {
	_, err := q.db.Exec(ctx, insertSentMessage,
		arg.ChatID,
		arg.ThreadID,
		arg.MessageID,
		arg.MessageIDStr,
		arg.Title,
		arg.SentAt,
		arg.ReportName,
		arg.ChType,
	)
	return err
}

const loadSentMsgsToDeleteForUpdate = `-- name: LoadSentMsgsToDeleteForUpdate :many
select id, chat_id, thread_id, message_id, message_id_str, title, sent_at, deleted, ch_type
from sent_messages
where deleted = false
  and sent_at >= CURRENT_DATE - INTERVAL '1 day'
  and sent_at < CURRENT_DATE
for update skip locked
`

type LoadSentMsgsToDeleteForUpdateRow struct {
	ID           int32
	ChatID       int64
	ThreadID     int32
	MessageID    int64
	MessageIDStr *string
	Title        string
	SentAt       pgtype.Timestamptz
	Deleted      bool
	ChType       string
}

func (q *Queries) LoadSentMsgsToDeleteForUpdate(ctx context.Context) ([]LoadSentMsgsToDeleteForUpdateRow, error) {
	rows, err := q.db.Query(ctx, loadSentMsgsToDeleteForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadSentMsgsToDeleteForUpdateRow
	for rows.Next() {
		var i LoadSentMsgsToDeleteForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ThreadID,
			&i.MessageID,
			&i.MessageIDStr,
			&i.Title,
			&i.SentAt,
			&i.Deleted,
			&i.ChType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEndOfDayMsgDeleted = `-- name: MarkEndOfDayMsgDeleted :exec
UPDATE sent_messages sm
SET deleted = TRUE
FROM (
    SELECT DISTINCT ON (report_name, chat_id)
        id
    FROM sent_messages
    WHERE deleted = FALSE
      AND sent_at >= CURRENT_DATE - INTERVAL '1 day'
      AND sent_at < CURRENT_DATE
    ORDER BY report_name, chat_id, sent_at DESC, id DESC
) last_msgs
WHERE sm.id = last_msgs.id
`

func (q *Queries) MarkEndOfDayMsgDeleted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markEndOfDayMsgDeleted)
	return err
}

const markSentMsgDeleted = `-- name: MarkSentMsgDeleted :exec
update sent_messages set deleted = true where id = $1
`

func (q *Queries) MarkSentMsgDeleted(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markSentMsgDeleted, id)
	return err
}
