// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one

insert into users(telegram_id, username, first_name, last_name, role)
values ($1, $2, $3, $4, $5)
returning id
`

type CreateUserParams struct {
	TelegramID int64
	Username   *string
	FirstName  *string
	LastName   *string
	Role       UserRole
}

// user.sql
// CRUD-запросы для таблицы users, используемые UserStore.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where telegram_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, telegramID)
	return err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
select id, telegram_id, username, first_name, last_name, role
from users
where telegram_id = $1
limit 1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, telegram_id, username, first_name, last_name, role
from users
where username = $1
limit 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Role,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
select id, telegram_id, username, first_name, last_name, role
from users
where role in ('admin', 'primary')
`

func (q *Queries) ListAdmins(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select id, telegram_id, username, first_name, last_name, role
from users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
update users
set telegram_id = $2,
    first_name  = $3,
    last_name   = $4
where username = $1
`

type UpdateUserParams struct {
	Username   *string
	TelegramID int64
	FirstName  *string
	LastName   *string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.TelegramID,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
