// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package orchestrator_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportLoader creates a new instance of MockReportLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportLoader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReportLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReportLoader is an autogenerated mock type for the ReportLoader type
type MockReportLoader struct {
	mock.Mock
}

type MockReportLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportLoader) EXPECT() *MockReportLoader_Expecter {
	return &MockReportLoader_Expecter{mock: &_m.Mock}
}

// LoadActive provides a mock function for the type MockReportLoader
func (_mock *MockReportLoader) LoadActive(ctx context.Context) ([]models.Report, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadActive")
	}

	var r0 []models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Report, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Report); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportLoader_LoadActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadActive'
type MockReportLoader_LoadActive_Call struct {
	*mock.Call
}

// LoadActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReportLoader_Expecter) LoadActive(ctx any) *MockReportLoader_LoadActive_Call {
	return &MockReportLoader_LoadActive_Call{Call: _e.mock.On("LoadActive", ctx)}
}

func (_c *MockReportLoader_LoadActive_Call) Run(run func(ctx context.Context)) *MockReportLoader_LoadActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportLoader_LoadActive_Call) Return(reports []models.Report, err error) *MockReportLoader_LoadActive_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *MockReportLoader_LoadActive_Call) RunAndReturn(run func(ctx context.Context) ([]models.Report, error)) *MockReportLoader_LoadActive_Call {
	_c.Call.Return(run)
	return _c
}

// LoadByEvent provides a mock function for the type MockReportLoader
func (_mock *MockReportLoader) LoadByEvent(ctx context.Context, event string, active bool) (*models.Report, error) {
	ret := _mock.Called(ctx, event, active)

	if len(ret) == 0 {
		panic("no return value specified for LoadByEvent")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Report, error)); ok {
		return returnFunc(ctx, event, active)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *models.Report); ok {
		r0 = returnFunc(ctx, event, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, event, active)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportLoader_LoadByEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadByEvent'
type MockReportLoader_LoadByEvent_Call struct {
	*mock.Call
}

// LoadByEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - active bool
func (_e *MockReportLoader_Expecter) LoadByEvent(ctx any, event any, active any) *MockReportLoader_LoadByEvent_Call {
	return &MockReportLoader_LoadByEvent_Call{Call: _e.mock.On("LoadByEvent", ctx, event, active)}
}

func (_c *MockReportLoader_LoadByEvent_Call) Run(run func(ctx context.Context, event string, active bool)) *MockReportLoader_LoadByEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportLoader_LoadByEvent_Call) Return(report *models.Report, err error) *MockReportLoader_LoadByEvent_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReportLoader_LoadByEvent_Call) RunAndReturn(run func(ctx context.Context, event string, active bool) (*models.Report, error)) *MockReportLoader_LoadByEvent_Call {
	_c.Call.Return(run)
	return _c
}
