// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportProvider creates a new instance of MockReportProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReportProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReportProvider is an autogenerated mock type for the ReportProvider type
type MockReportProvider struct {
	mock.Mock
}

type MockReportProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportProvider) EXPECT() *MockReportProvider_Expecter {
	return &MockReportProvider_Expecter{mock: &_m.Mock}
}

// GetByName provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) GetByName(ctx context.Context, reportName string) (*models.Report, error) {
	ret := _mock.Called(ctx, reportName)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Report, error)); ok {
		return returnFunc(ctx, reportName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Report); ok {
		r0 = returnFunc(ctx, reportName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reportName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportProvider_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockReportProvider_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - reportName string
func (_e *MockReportProvider_Expecter) GetByName(ctx any, reportName any) *MockReportProvider_GetByName_Call {
	return &MockReportProvider_GetByName_Call{Call: _e.mock.On("GetByName", ctx, reportName)}
}

func (_c *MockReportProvider_GetByName_Call) Run(run func(ctx context.Context, reportName string)) *MockReportProvider_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_GetByName_Call) Return(report *models.Report, err error) *MockReportProvider_GetByName_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReportProvider_GetByName_Call) RunAndReturn(run func(ctx context.Context, reportName string) (*models.Report, error)) *MockReportProvider_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedCrons provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) GetLinkedCrons(ctx context.Context, reportName string) ([]models.SheduleUnit, error) {
	ret := _mock.Called(ctx, reportName)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedCrons")
	}

	var r0 []models.SheduleUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.SheduleUnit, error)); ok {
		return returnFunc(ctx, reportName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.SheduleUnit); ok {
		r0 = returnFunc(ctx, reportName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SheduleUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reportName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportProvider_GetLinkedCrons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedCrons'
type MockReportProvider_GetLinkedCrons_Call struct {
	*mock.Call
}

// GetLinkedCrons is a helper method to define mock.On call
//   - ctx context.Context
//   - reportName string
func (_e *MockReportProvider_Expecter) GetLinkedCrons(ctx any, reportName any) *MockReportProvider_GetLinkedCrons_Call {
	return &MockReportProvider_GetLinkedCrons_Call{Call: _e.mock.On("GetLinkedCrons", ctx, reportName)}
}

func (_c *MockReportProvider_GetLinkedCrons_Call) Run(run func(ctx context.Context, reportName string)) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_GetLinkedCrons_Call) Return(sheduleUnits []models.SheduleUnit, err error) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Return(sheduleUnits, err)
	return _c
}

func (_c *MockReportProvider_GetLinkedCrons_Call) RunAndReturn(run func(ctx context.Context, reportName string) ([]models.SheduleUnit, error)) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPaged provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) LoadPaged(ctx context.Context, page int) ([]models.ReportForTgLK, int, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for LoadPaged")
	}

	var r0 []models.ReportForTgLK
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.ReportForTgLK, int, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.ReportForTgLK); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReportForTgLK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, page)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReportProvider_LoadPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPaged'
type MockReportProvider_LoadPaged_Call struct {
	*mock.Call
}

// LoadPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
func (_e *MockReportProvider_Expecter) LoadPaged(ctx any, page any) *MockReportProvider_LoadPaged_Call {
	return &MockReportProvider_LoadPaged_Call{Call: _e.mock.On("LoadPaged", ctx, page)}
}

func (_c *MockReportProvider_LoadPaged_Call) Run(run func(ctx context.Context, page int)) *MockReportProvider_LoadPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_LoadPaged_Call) Return(reportForTgLKs []models.ReportForTgLK, n int, err error) *MockReportProvider_LoadPaged_Call {
	_c.Call.Return(reportForTgLKs, n, err)
	return _c
}

func (_c *MockReportProvider_LoadPaged_Call) RunAndReturn(run func(ctx context.Context, page int) ([]models.ReportForTgLK, int, error)) *MockReportProvider_LoadPaged_Call {
	_c.Call.Return(run)
	return _c
}
