// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mock

import (
	"context"
	"support_bot/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatProvider creates a new instance of MockChatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockChatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockChatProvider is an autogenerated mock type for the ChatProvider type
type MockChatProvider struct {
	mock.Mock
}

type MockChatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatProvider) EXPECT() *MockChatProvider_Expecter {
	return &MockChatProvider_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatProvider
func (_mock *MockChatProvider) Create(ctx context.Context, chat *models.TgChatDTO) error {
	ret := _mock.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TgChatDTO) error); ok {
		r0 = returnFunc(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *models.TgChatDTO
func (_e *MockChatProvider_Expecter) Create(ctx any, chat any) *MockChatProvider_Create_Call {
	return &MockChatProvider_Create_Call{Call: _e.mock.On("Create", ctx, chat)}
}

func (_c *MockChatProvider_Create_Call) Run(run func(ctx context.Context, chat *models.TgChatDTO)) *MockChatProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TgChatDTO
		if args[1] != nil {
			arg1 = args[1].(*models.TgChatDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatProvider_Create_Call) Return(err error) *MockChatProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatProvider_Create_Call) RunAndReturn(run func(ctx context.Context, chat *models.TgChatDTO) error) *MockChatProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatProvider
func (_mock *MockChatProvider) Delete(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockChatProvider_Expecter) Delete(ctx any, chatID any) *MockChatProvider_Delete_Call {
	return &MockChatProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, chatID)}
}

func (_c *MockChatProvider_Delete_Call) Run(run func(ctx context.Context, chatID int64)) *MockChatProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatProvider_Delete_Call) Return(err error) *MockChatProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockChatProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockChatProvider
func (_mock *MockChatProvider) Exists(ctx context.Context, chatID int64) (bool, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockChatProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockChatProvider_Expecter) Exists(ctx any, chatID any) *MockChatProvider_Exists_Call {
	return &MockChatProvider_Exists_Call{Call: _e.mock.On("Exists", ctx, chatID)}
}

func (_c *MockChatProvider_Exists_Call) Run(run func(ctx context.Context, chatID int64)) *MockChatProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatProvider_Exists_Call) Return(b bool, err error) *MockChatProvider_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChatProvider_Exists_Call) RunAndReturn(run func(ctx context.Context, chatID int64) (bool, error)) *MockChatProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockChatProvider
func (_mock *MockChatProvider) GetAll(ctx context.Context) ([]models.TgChatDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.TgChatDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.TgChatDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.TgChatDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TgChatDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockChatProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatProvider_Expecter) GetAll(ctx any) *MockChatProvider_GetAll_Call {
	return &MockChatProvider_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockChatProvider_GetAll_Call) Run(run func(ctx context.Context)) *MockChatProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatProvider_GetAll_Call) Return(tgChatDTOs []models.TgChatDTO, err error) *MockChatProvider_GetAll_Call {
	_c.Call.Return(tgChatDTOs, err)
	return _c
}

func (_c *MockChatProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.TgChatDTO, error)) *MockChatProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTitle provides a mock function for the type MockChatProvider
func (_mock *MockChatProvider) GetByTitle(ctx context.Context, title string) (*models.TgChatDTO, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for GetByTitle")
	}

	var r0 *models.TgChatDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.TgChatDTO, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.TgChatDTO); ok {
		r0 = returnFunc(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TgChatDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatProvider_GetByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTitle'
type MockChatProvider_GetByTitle_Call struct {
	*mock.Call
}

// GetByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockChatProvider_Expecter) GetByTitle(ctx any, title any) *MockChatProvider_GetByTitle_Call {
	return &MockChatProvider_GetByTitle_Call{Call: _e.mock.On("GetByTitle", ctx, title)}
}

func (_c *MockChatProvider_GetByTitle_Call) Run(run func(ctx context.Context, title string)) *MockChatProvider_GetByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatProvider_GetByTitle_Call) Return(tgChatDTO *models.TgChatDTO, err error) *MockChatProvider_GetByTitle_Call {
	_c.Call.Return(tgChatDTO, err)
	return _c
}

func (_c *MockChatProvider_GetByTitle_Call) RunAndReturn(run func(ctx context.Context, title string) (*models.TgChatDTO, error)) *MockChatProvider_GetByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminNotifier creates a new instance of MockAdminNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminNotifier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAdminNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAdminNotifier is an autogenerated mock type for the AdminNotifier type
type MockAdminNotifier struct {
	mock.Mock
}

type MockAdminNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminNotifier) EXPECT() *MockAdminNotifier_Expecter {
	return &MockAdminNotifier_Expecter{mock: &_m.Mock}
}

// GetAllAdmins provides a mock function for the type MockAdminNotifier
func (_mock *MockAdminNotifier) GetAllAdmins(ctx context.Context) ([]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAdmins")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminNotifier_GetAllAdmins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAdmins'
type MockAdminNotifier_GetAllAdmins_Call struct {
	*mock.Call
}

// GetAllAdmins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminNotifier_Expecter) GetAllAdmins(ctx any) *MockAdminNotifier_GetAllAdmins_Call {
	return &MockAdminNotifier_GetAllAdmins_Call{Call: _e.mock.On("GetAllAdmins", ctx)}
}

func (_c *MockAdminNotifier_GetAllAdmins_Call) Run(run func(ctx context.Context)) *MockAdminNotifier_GetAllAdmins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminNotifier_GetAllAdmins_Call) Return(users []models.User, err error) *MockAdminNotifier_GetAllAdmins_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAdminNotifier_GetAllAdmins_Call) RunAndReturn(run func(ctx context.Context) ([]models.User, error)) *MockAdminNotifier_GetAllAdmins_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportProvider creates a new instance of MockReportProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReportProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReportProvider is an autogenerated mock type for the ReportProvider type
type MockReportProvider struct {
	mock.Mock
}

type MockReportProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportProvider) EXPECT() *MockReportProvider_Expecter {
	return &MockReportProvider_Expecter{mock: &_m.Mock}
}

// GetByName provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) GetByName(ctx context.Context, reportName string) (*models.Report, error) {
	ret := _mock.Called(ctx, reportName)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Report, error)); ok {
		return returnFunc(ctx, reportName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Report); ok {
		r0 = returnFunc(ctx, reportName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reportName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportProvider_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockReportProvider_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - reportName string
func (_e *MockReportProvider_Expecter) GetByName(ctx any, reportName any) *MockReportProvider_GetByName_Call {
	return &MockReportProvider_GetByName_Call{Call: _e.mock.On("GetByName", ctx, reportName)}
}

func (_c *MockReportProvider_GetByName_Call) Run(run func(ctx context.Context, reportName string)) *MockReportProvider_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_GetByName_Call) Return(report *models.Report, err error) *MockReportProvider_GetByName_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReportProvider_GetByName_Call) RunAndReturn(run func(ctx context.Context, reportName string) (*models.Report, error)) *MockReportProvider_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedCrons provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) GetLinkedCrons(ctx context.Context, reportName string) ([]models.SheduleUnit, error) {
	ret := _mock.Called(ctx, reportName)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedCrons")
	}

	var r0 []models.SheduleUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.SheduleUnit, error)); ok {
		return returnFunc(ctx, reportName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.SheduleUnit); ok {
		r0 = returnFunc(ctx, reportName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SheduleUnit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reportName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportProvider_GetLinkedCrons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedCrons'
type MockReportProvider_GetLinkedCrons_Call struct {
	*mock.Call
}

// GetLinkedCrons is a helper method to define mock.On call
//   - ctx context.Context
//   - reportName string
func (_e *MockReportProvider_Expecter) GetLinkedCrons(ctx any, reportName any) *MockReportProvider_GetLinkedCrons_Call {
	return &MockReportProvider_GetLinkedCrons_Call{Call: _e.mock.On("GetLinkedCrons", ctx, reportName)}
}

func (_c *MockReportProvider_GetLinkedCrons_Call) Run(run func(ctx context.Context, reportName string)) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_GetLinkedCrons_Call) Return(sheduleUnits []models.SheduleUnit, err error) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Return(sheduleUnits, err)
	return _c
}

func (_c *MockReportProvider_GetLinkedCrons_Call) RunAndReturn(run func(ctx context.Context, reportName string) ([]models.SheduleUnit, error)) *MockReportProvider_GetLinkedCrons_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPaged provides a mock function for the type MockReportProvider
func (_mock *MockReportProvider) LoadPaged(ctx context.Context, page int) ([]models.ReportForTgLK, int, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for LoadPaged")
	}

	var r0 []models.ReportForTgLK
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.ReportForTgLK, int, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.ReportForTgLK); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReportForTgLK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, page)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReportProvider_LoadPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPaged'
type MockReportProvider_LoadPaged_Call struct {
	*mock.Call
}

// LoadPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
func (_e *MockReportProvider_Expecter) LoadPaged(ctx any, page any) *MockReportProvider_LoadPaged_Call {
	return &MockReportProvider_LoadPaged_Call{Call: _e.mock.On("LoadPaged", ctx, page)}
}

func (_c *MockReportProvider_LoadPaged_Call) Run(run func(ctx context.Context, page int)) *MockReportProvider_LoadPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportProvider_LoadPaged_Call) Return(reportForTgLKs []models.ReportForTgLK, n int, err error) *MockReportProvider_LoadPaged_Call {
	_c.Call.Return(reportForTgLKs, n, err)
	return _c
}

func (_c *MockReportProvider_LoadPaged_Call) RunAndReturn(run func(ctx context.Context, page int) ([]models.ReportForTgLK, int, error)) *MockReportProvider_LoadPaged_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) Create(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserProvider_Expecter) Create(ctx any, user any) *MockUserProvider_Create_Call {
	return &MockUserProvider_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserProvider_Create_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_Create_Call) Return(err error) *MockUserProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_Create_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) Delete(ctx context.Context, tgID int64) error {
	ret := _mock.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, tgID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
func (_e *MockUserProvider_Expecter) Delete(ctx any, tgID any) *MockUserProvider_Delete_Call {
	return &MockUserProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, tgID)}
}

func (_c *MockUserProvider_Delete_Call) Run(run func(ctx context.Context, tgID int64)) *MockUserProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_Delete_Call) Return(err error) *MockUserProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, tgID int64) error) *MockUserProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetAll(ctx context.Context) ([]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUserProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserProvider_Expecter) GetAll(ctx any) *MockUserProvider_GetAll_Call {
	return &MockUserProvider_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockUserProvider_GetAll_Call) Run(run func(ctx context.Context)) *MockUserProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetAll_Call) Return(users []models.User, err error) *MockUserProvider_GetAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.User, error)) *MockUserProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTgID provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByTgID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetByTgID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTgID'
type MockUserProvider_GetByTgID_Call struct {
	*mock.Call
}

// GetByTgID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserProvider_Expecter) GetByTgID(ctx any, id any) *MockUserProvider_GetByTgID_Call {
	return &MockUserProvider_GetByTgID_Call{Call: _e.mock.On("GetByTgID", ctx, id)}
}

func (_c *MockUserProvider_GetByTgID_Call) Run(run func(ctx context.Context, id int64)) *MockUserProvider_GetByTgID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetByTgID_Call) Return(user *models.User, err error) *MockUserProvider_GetByTgID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_GetByTgID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*models.User, error)) *MockUserProvider_GetByTgID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetByUsername(ctx context.Context, username string) (*models.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserProvider_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserProvider_Expecter) GetByUsername(ctx any, username any) *MockUserProvider_GetByUsername_Call {
	return &MockUserProvider_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserProvider_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserProvider_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetByUsername_Call) Return(user *models.User, err error) *MockUserProvider_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*models.User, error)) *MockUserProvider_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) Update(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserProvider_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserProvider_Expecter) Update(ctx any, user any) *MockUserProvider_Update_Call {
	return &MockUserProvider_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserProvider_Update_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserProvider_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_Update_Call) Return(err error) *MockUserProvider_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_Update_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserProvider_Update_Call {
	_c.Call.Return(run)
	return _c
}
